### ISSUE TITLE
two different @pages

### ISSUE THREAD

**Issue by prinla** [getgrav/grav-plugin-relatedpages#13]
Hello,
With the filter items '@page': /erpeldange the plugin works pretty good.
On all the pages in /erpeldange the related posts are shown...

But my website is divided in 2 main parts: /erpeldange & /colmar

And I would like to show related articles also on the /colmar part...
How can I do that? Add something in the frontmatter of the colmar-pages?

I tried with the taxonomy.tag but the results were not satisfying...

Any other solution?

**Comment by flaviocopes** [comment]
It's a Collection, so you can sum 2 collections using https://learn.getgrav.org/content/collections#complex-collections

**Comment by X-Ryl669** [comment]
It broke for me when going to Grav 1.7, but it's fixable manually this way (**never edit in admin interface, it'll break the result**):
Open `/user/config/relatedpages.yaml`, and it should read:
```yaml
enabled: true
limit: 5
show_score: true
score_threshold: 20
filter:
  items:
    - '@page':
      - /software
    - '@page':
      - /3d-printers
    - '@page':
      - /documentation
  order:
    by: date
    dir: desc
page_in_filter: true
explicit_pages:
  process: true
  score: 100
taxonomy_match:
  taxonomy:
    - tag
  taxonomy_taxonomy:
    process: true
    score_scale:
      1: '50'
      2: '75'
      3: '100'
  taxonomy_content:
    process: true
    score_scale:
      1: '20'
      2: '30'
      3: '45'
      4: '60'
      5: '70'
      6: '80'
      7: '90'
      8: '100'
content_match:
  process: false
```
The important part is the in the `filters/items` section, you'll need to change `@page`  to `- @page` and duplicate and adapt for each master page you want your plugin to work with.
