### ISSUE TITLE
Config creates invalid yaml

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-relatedpages#17]
So, after hours and hours of trying to find why I was not able to use relatedpages, I finally found what was the cause of the problem.

## Step to replicate
Install relatedpages plugin.
the default relatedpages.yaml looks like this:

```
enabled: true                   # set to false to disable this plugin completely
limit: 5                        # the number of related pages to display
show_score: true                # toggle to determine if scores should be displayed in output
score_threshold: 20 # minimum score needed to show up in the list
filter:                         # filter a configurable collection of pages to compare
    items:
        @page: /blog            # supports @self, @page, and @taxonomy collections
    order:
        by: date                # order type by default
        dir: desc               # order direction
page_in_filter: true            # true if the current page must be in the filtered collection
explicit_pages:
    process: true               # true|flase to enable this explicit page matching
    score: 100
```

Now, within the admin, when clicking on save, the yaml validation will generate this in user/config/relatedpages.yaml:
```
enabled: true
limit: 5
show_score: true
score_threshold: 20
filter:
  items: '''@page'': /blog'
  order:
    by: date
    dir: desc
page_in_filter: true
explicit_pages:
  process: true
  score: 100
```
Which simply does not work.

I was already feeling like something was wrong with this blueprint so I made this PR a while ago: https://github.com/getgrav/grav-plugin-relatedpages/pull/14

But I don't think this is the solution neither.

Let me know if more info is needed.
